### ISSUE TITLE
Add conditional classes

### ISSUE THREAD

**Issue by Bloomca** [Bloomca/js-bemto#1]
In order to avoid cluttering as next:
```javascript
const eventAnnounceClassName = b(
  `${isActive ? '__active' : ''}.` +
  `${isPast   ? '__past'   : '' }.` +
  `${isDark   ? '__dark'   : '' }`);
```

and replace it with next approach:

```javascript
const eventAnnounceClassName = b(`__active?${isActive}.__past?${isPast}._dark?${isDark}`);
```

**Comment by tadjik1** [comment]
what do you think about pass this mods via object?

```javascript
const eventAnnounceClassName = b(
  __active: isActive,
  __past: isPast,
  __dark: isDark
);
```

it could be more useful than string

**Comment by Bloomca** [comment]
@tadjik1 Well, if we will have more than 2 (maybe 3 at max) this approach is definitely better.
Good idea, but here we have some subtle points – how to distinct blocks and elems.

For now, I see this solution: 
```javascript
const eventAnnounceClassName = b({
  '&block': 'title',
  __active: isActive,
  __past: isPast,
  __dark: isDark
});
```

It is for block. We could derive info about block or elem (and corresponding value) only in case of string – we take first value.
In terms of block we could pass any truthy value to ensure we deal with block.

For elem it would be smth like:

```javascript
const eventTitle = e({
  '&elem': 'title',
  __dark: isDark,
  __filled: isFilled,
  __active: isActive
});
```

Though I don't think string is a bad idea. Consider two modifiers, then we will have next code:
```javascript
const eventTitle = e(`title.__dark?${isDark}.__active?${isActive}`);
```

Much more concise!

**Comment by Bloomca** [comment]
Though I though a bit more and realized that '&block' is redundant, we could stick just with '&elem' – if we don't have one, then we should think we deal with block.

I wonder how it is applicable to constructor, but for now I prefer to instantiate class generator in closure.

**Comment by Bloomca** [comment]
Added both syntaxes – https://github.com/Bloomca/js-bemto/pull/2
